# Generated by Django 3.1.2 on 2020-10-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='static/broken.png', upload_to='static/media'),
        ),
    ]
